name: Sync issues to jira
on:
  issues:
    types: [labeled]

jobs:
  create-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Jira Issue
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: "https://droidsonroids.atlassian.net"
        run: |
          ISSUE_SUMMARY="Brief summary of the issue"
          ISSUE_DESCRIPTION="Detailed description of the issue"
          curl -X POST \
          -u "yevhenii.oros@droidsonroids.pl:${JIRA_API_TOKEN}" \
          -H "Content-Type: application/json" \
          -d '{
            "fields": {
              "project": {
                "key": "FT"
              },
              "summary": "Brief summary of the issuee",
              "description": "Detailed description of the issue",
              "issuetype": {
                "name": "Task"
              }
            }
          }' \
          $JIRA_BASE_URL/rest/api/2/issue/
