name: Sync issues to jira
on:
  issues:
    types: [labeled]
jobs:
  issue-sync:
    permissions:
      issues: write # should be set
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Jira
        uses: atsushii/github-issue-to-jira@v1
        with:
          github-owner: DroidsOnRoids
          github-repo: add-to-google-wallet
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-hostname: https://id.atlassian.com
          jira-auth-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-auth-email: ${{ secrets.JIRA_AUTH_EMAIL }}
          jira-project-key: FT